sonar.projectName=SIGA Cloud Native Flow Frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=src/**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info
sonar.sourceEncoding=UTF-8
