{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "todo-platform.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "todo-platform.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  selector:
    matchLabels:
      {{- include "todo-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: {{ .Values.monitoring.scrapeInterval }}
      scheme: http
{{- end }}
